#!/usr/bin/env python3
"""Convert sprite images into text and C-friendly ASCII art snippets."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

INPUT_DIR = Path(__file__).parent / "input"
OUTPUT_DIR = Path(__file__).parent / "output"
GENERATED_DIR = Path(__file__).parent / "generated"

DEFAULT_CHARS = " .:-=+*#%@"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert one sprite image into ASCII art text and a C string snippet.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "image",
        type=Path,
        help="Input sprite image path. Relative paths are resolved from this directory's input/ folder first.",
    )
    parser.add_argument(
        "-w",
        "--width",
        type=int,
        default=48,
        help="Output ASCII width in characters.",
    )
    parser.add_argument(
        "--chars",
        default=DEFAULT_CHARS,
        help="Characters from darkest to brightest pixel.",
    )
    parser.add_argument(
        "--invert",
        action="store_true",
        help="Reverse the brightness-to-character mapping.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Human-readable ASCII text output path.",
    )
    parser.add_argument(
        "--generated",
        type=Path,
        help="C-friendly generated snippet output path.",
    )
    parser.add_argument(
        "--c-name",
        help="C variable name for the generated snippet.",
    )
    return parser.parse_args()


def resolve_input(path: Path) -> Path:
    if path.exists():
        return path

    input_path = INPUT_DIR / path
    if input_path.exists():
        return input_path

    raise FileNotFoundError(f"input image not found: {path}")


def safe_c_identifier(name: str) -> str:
    identifier = re.sub(r"\W+", "_", name.strip().lower())
    identifier = identifier.strip("_") or "sprite"
    if identifier[0].isdigit():
        identifier = f"sprite_{identifier}"
    return identifier


def load_image(path: Path):
    try:
        from PIL import Image
    except ImportError as exc:
        raise RuntimeError(
            "Pillow is required for image conversion. Install it with: python3 -m pip install Pillow"
        ) from exc

    return Image.open(path).convert("RGBA")


def image_to_ascii(image, width: int, chars: str, invert: bool) -> list[str]:
    if width <= 0:
        raise ValueError("width must be greater than 0")
    if len(chars) < 2:
        raise ValueError("chars must contain at least two characters")

    if invert:
        chars = chars[::-1]

    source_width, source_height = image.size
    if source_width <= 0 or source_height <= 0:
        raise ValueError("image has invalid dimensions")

    # Text cells are usually taller than they are wide, so reduce the image height.
    aspect_ratio = source_height / source_width
    height = max(1, round(width * aspect_ratio * 0.5))
    from PIL import Image

    resample = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
    resized = image.resize((width, height), resample)

    rows: list[str] = []
    max_index = len(chars) - 1
    for y in range(height):
        row_chars: list[str] = []
        for x in range(width):
            red, green, blue, alpha = resized.getpixel((x, y))
            if alpha < 20:
                row_chars.append(" ")
                continue

            brightness = (0.299 * red) + (0.587 * green) + (0.114 * blue)
            index = round((brightness / 255) * max_index)
            row_chars.append(chars[index])
        rows.append("".join(row_chars).rstrip())

    return rows


def write_text_output(path: Path, rows: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")


def c_escape(line: str) -> str:
    return line.replace("\\", "\\\\").replace('"', '\\"')


def write_c_output(path: Path, rows: list[str], c_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    width = max((len(row) for row in rows), default=0)
    lines = [
        "/* Generated by tools/ascii_converter/convert_sprite.py */",
        f"static const char *{c_name}[] = {{",
    ]
    lines.extend(f'    "{c_escape(row)}",' for row in rows)
    lines.extend(
        [
            "};",
            f"static const int {c_name}_width = {width};",
            f"static const int {c_name}_height = {len(rows)};",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def default_output_paths(image_path: Path) -> tuple[Path, Path]:
    return OUTPUT_DIR / f"{image_path.stem}.txt", GENERATED_DIR / f"{image_path.stem}.inc"


def main() -> None:
    args = parse_args()

    try:
        image_path = resolve_input(args.image)
        text_output, c_output = default_output_paths(image_path)
        text_output = args.output or text_output
        c_output = args.generated or c_output
        c_name = safe_c_identifier(args.c_name or f"{image_path.stem}_ascii")

        image = load_image(image_path)
        rows = image_to_ascii(image, args.width, args.chars, args.invert)
        write_text_output(text_output, rows)
        write_c_output(c_output, rows, c_name)
    except (FileNotFoundError, OSError, RuntimeError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc

    print(f"Wrote text ASCII: {text_output}")
    print(f"Wrote C snippet:   {c_output}")


if __name__ == "__main__":
    main()
